### PR TITLE
Rebase "Add HTTPS health check"

### PR DESCRIPTION
**Pull request by Freggy**
Rebase PR https://github.com/openresty/lua-resty-upstream-healthcheck/pull/81

### CODE REVIEW

**Comment by zhuizhuhaomeng** [comment]
ci failed, please move the new test to another file https.t

**Comment by Freggy** [comment]
fixed

**Comment by Freggy** [comment]
sorry for ping, but any ETA when you can merge this @zhuizhuhaomeng? or is there something missing, that i am not aware of?

**Comment by zhuizhuhaomeng** [comment]
> sorry for ping, but any ETA when you can merge this @zhuizhuhaomeng? or is there something missing, that i am not aware of?

thank you for your contribution.

**Pull request merged**
